- name: Disable Default Version of NodeJS
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS18 Version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Configure Backend Service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application User
  ansible.builtin.user:
    name: expense

- name: App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Downloading Application Dependencies
  community.general.npm:
    path: /app

- name: Start MySql Service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes

- name: Install MySql & Python Library for MySql
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
    - mysql
    - python3-PyMySQL

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: "{{ lookup('amazon.aws.aws_ssm', 'dev.mysql.root_password', region='us-east-1') }}"
    login_host: mysql-dev.kdevops.online