- name: Reset NodeJS module
  shell: dnf module reset nodejs -y

- name: Remove existing NodeJS
  dnf:
    name: nodejs
    state: absent

- name: Enable NodeJS 20
  shell: dnf module enable nodejs:20 -y

- name: Install NodeJS
  dnf:
    name: nodejs
    state: installed

- name: Verify NodeJS version
  command: node -v
  register: node_version

- debug:
    msg: "Node version is {{ node_version.stdout }}"

- name: Add application user
  user:
    name: expense

- name: App prerequisites
  include_role:
    name: common
    tasks_from: app_prereq

- name: Install app dependencies
  community.general.npm:
    path: /app
  become: yes
  become_user: expense

- name: Install New Relic
  shell: npm install newrelic --save
  args:
    chdir: /app
  become: yes
  become_user: expense

- name: Configure backend service
  template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Reload systemd and start backend
  systemd_service:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes


- name: Install MySql & Python Library for MySql
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
    - mysql
    - python3-PyMySQL

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.username', region='us-east-1') }}"
    login_password: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.password', region='us-east-1') }}"
    login_host: "{{ lookup('amazon.aws.aws_ssm', '{{env}}.expense.rds.endpoint', region='us-east-1') }}"



