
  - name: Install the latest version of Nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: Copying Expense configuartion file
    ansible.builtin.template:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: App Prerequisites
    ansible.builtin.include_role:
      name: common
      tasks_from: app_prereq


  - name: Start Nginx Service
    ansible.builtin.systemd_service:
      name: nginx
      enabled: true
      state: restarted




