- name: Delete existing content
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory
    owner: "{{app_user}}"

- name: Downaload and extract App Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: "{{ app_path }}"
    remote_src: yes
